import type { AssistSettings } from './types.js';

export const DEFAULT_SETTINGS: AssistSettings = {
  settingsVersion: 13,
  assistProfile: 'auto',
  mode: 'auto',
  modules: {
    healing: true,
    damageToHeal: true,
    defensives: true,
    interrupts: true,
    resurrection: false,
  },
  abilities: {
    arcane_intellect: true,
    frost_armor: true,
    frostbolt: true,
    ice_lance: true,
    flurry: true,
    frozen_orb: true,
    blizzard: true,
    glacial_spike: true,
    glacial_front: true,
    ice_barrier: true,
    icy_veins: true,
    summon_water_elemental: true,
    cone_of_cold: true,
    presence_of_mind: true,
    rune_of_power: true,
    ice_floes: false,
    cold_snap: true,
    greater_invisibility: false,
    rings_of_frost: false,
    temporal_echo: true,
    temporal_mend: true,
    temporal_barrier: true,
    temporal_cascade: true,
    temporal_rewind: true,
    mass_barrier: true,
    power_echo: true,
    arcane_surge: true,
    arcane_missiles: true,
    arcane_explosion: true,
    evocation: true,
    perfect_moment: false,
    counterspell: true,
    ice_block: true,
    blink: true,
    frost_nova: true,
    polymorph: true,
    temporal_hourglass: true,
    temporal_acceleration: true,
    temporal_reversal: false,
    collective_reversal: false,
  },
  frostAbilities: {
    arcane_intellect: true,
    frost_armor: true,
    frostbolt: true,
    ice_lance: true,
    flurry: true,
    frozen_orb: true,
    blizzard: true,
    glacial_spike: true,
    glacial_front: true,
    ice_barrier: true,
    icy_veins: true,
    summon_water_elemental: true,
    cone_of_cold: true,
    power_echo: true,
    presence_of_mind: true,
    rune_of_power: true,
    counterspell: true,
    ice_block: true,
    evocation: true,
    frost_nova: true,
  },
  profiles: {
    solo: {
      mendHpPct: 0.72,
      barrierHpPct: 0.82,
      emergencyHpPct: 0.48,
      cascadeHpPct: 0.85,
      cascadeCount: 1,
      massBarrierHpPct: 0.75,
      massBarrierCount: 1,
      rewindLossPct: 0.2,
      rewindCount: 1,
      conserveManaPct: 0.45,
      stopDamageManaPct: 0.2,
    },
    party: {
      mendHpPct: 0.7,
      barrierHpPct: 0.8,
      emergencyHpPct: 0.45,
      cascadeHpPct: 0.85,
      cascadeCount: 2,
      massBarrierHpPct: 0.75,
      massBarrierCount: 2,
      rewindLossPct: 0.2,
      rewindCount: 2,
      conserveManaPct: 0.5,
      stopDamageManaPct: 0.25,
    },
    raid: {
      mendHpPct: 0.75,
      barrierHpPct: 0.82,
      emergencyHpPct: 0.5,
      cascadeHpPct: 0.88,
      cascadeCount: 3,
      massBarrierHpPct: 0.78,
      massBarrierCount: 3,
      rewindLossPct: 0.18,
      rewindCount: 3,
      conserveManaPct: 0.55,
      stopDamageManaPct: 0.35,
    },
    pvp: {
      mendHpPct: 0.72,
      barrierHpPct: 0.88,
      emergencyHpPct: 0.52,
      cascadeHpPct: 0.82,
      cascadeCount: 2,
      massBarrierHpPct: 0.76,
      massBarrierCount: 2,
      rewindLossPct: 0.15,
      rewindCount: 1,
      conserveManaPct: 0,
      stopDamageManaPct: 0,
    },
  },
  frost: {
    autoSummonWaterElemental: true,
    blizzardEnemyCount: 3,
    frozenOrbEnemyCount: 3,
    glacialFrontEnemyCount: 3,
    conserveManaPct: 0.25,
    stopDamageManaPct: 0.05,
    aetherwellManaPct: 0.3,
    barrierHpPct: 0.72,
    iceBlockHpPct: 0.28,
    icyVeinsDurableOnly: true,
    smartProcs: true,
    smartGlacialBurst: true,
    useIcebindPve: true,
  },
  thresholds: {
    aetherwellManaPct: 0.35,
    echoRefreshSeconds: 1,
    smartPowerEcho: true,
    smartPerfectMoment: false,
    smartSurgeCharges: true,
    maxSurgeCharges: 2,
    lowManaMaxSurgeCharges: 1,
    aoeEnemyCount: 3,
  },
  targeting: {
    assignedTankId: null,
    assistMemberId: null,
    enemyMode: 'tank-target',
    friendlyMode: 'lowest-effective-hp',
    keepEchoOnTank: true,
    partyOnly: true,
    autoPull: true,
    maxTargetRange: 30,
    streamTargetSelection: true,
  },
  consumables: {
    healthPotion: true,
    healthPotionHpPct: 0.3,
    manaPotion: true,
    manaPotionManaPct: 0.2,
  },
  pvp: {
    enabled: true,
    minSurgeCharges: 1,
    maxSurgeCharges: 4,
    iceBlockHpPct: 0.45,
    blinkOnRoot: true,
    frostNovaHpPct: 0.7,
    frostNovaEnemyCount: 2,
    polymorphHpPct: 0.6,
    hourglassHpPct: 0.4,
  },
  safety: {
    manualOverrideMs: 2000,
    disableInPvp: false,
    buffOutOfCombat: true,
    decisionIntervalMs: 100,
    toggleHotkey: '[',
  },
};

export function copyDefaultSettings(): AssistSettings {
  return structuredClone(DEFAULT_SETTINGS);
}
